# Generated by Django 3.0.6 on 2020-05-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fcuser',
            new_name='hyuser',
        ),
    ]
