# Generated by Django 3.0.6 on 2020-05-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200504_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registered_dttm',
            new_name='register_date',
        ),
    ]
