# Generated by Django 3.0.6 on 2020-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200522_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='주문 총액'),
            preserve_default=False,
        ),
    ]
