# Generated by Django 3.0.6 on 2020-05-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hyuser',
            old_name='regstered_dttm',
            new_name='registered_dttm',
        ),
    ]
