# Generated by Django 3.0.6 on 2020-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuser', '0002_auto_20200504_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyuser',
            name='level',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
