# Generated by Django 3.0.6 on 2020-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyuser', '0003_hyuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
    ]
